--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ByAlperenS/Furnace
build-by-default: true
branches:
- master
projects:
  Furnace:
    path: ""
    libs: 
    - src: muqsit/InvMenu/InvMenu
      version: ^2.1.0
...
